export enum PolicyAction {
  VIEW_OBSERVER_DASHBOARD = 'VIEW_OBSERVER_DASHBOARD',
  VIEW_LIVE_TOUR = 'VIEW_LIVE_TOUR',
  VIEW_AUDIT_TIMELINE = 'VIEW_AUDIT_TIMELINE',
  EXPORT_AUDIT_DATA = 'EXPORT_AUDIT_DATA',
  CREATE_TOUR = 'CREATE_TOUR',
  PUBLISH_TOUR = 'PUBLISH_TOUR',
}
