# ============================================
# Stage 1: BASE — shared Alpine image with system deps
# ============================================
# All stages inherit from this to ensure consistent Node + OS versions.
# libc6-compat is required for Alpine musl/glibc compat (Next.js, Prisma).
# openssl is required by Prisma query engine on Alpine.
FROM node:20-alpine AS base
RUN apk add --no-cache libc6-compat openssl

# ============================================
# Stage 2: DEPS — install all npm dependencies
# ============================================
# Copies only package manifests first for optimal Docker layer caching.
# Includes devDependencies because they're needed for the build step.
# python3/make/g++ are needed to compile native addons (bcrypt).
FROM base AS deps
RUN apk add --no-cache python3 make g++
WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma/schema.prisma ./prisma/schema.prisma
RUN npm ci --legacy-peer-deps

# ============================================
# Stage 3: BUILDER — generate Prisma client + build Next.js
# ============================================
# Runs prisma generate (produces query engine for Alpine) then next build.
# output: 'standalone' in next.config.js produces a self-contained server
# at .next/standalone that doesn't need node_modules at runtime.
FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Ensure public directory exists (even if empty)
RUN mkdir -p public

# Generate Prisma client with Alpine-compatible binary
RUN npx prisma generate

# Build the Next.js application in production mode
ENV NODE_ENV=production
RUN npm run build

# ============================================
# Stage 4: RUNNER — minimal production image
# ============================================
# Contains ONLY the standalone server output, public assets, and static files.
# No node_modules, no source code, no devDependencies.
# Runs as non-root user for security hardening.
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

# Create non-root user
RUN addgroup --system --gid 1001 nodejs && \
  adduser --system --uid 1001 nextjs

# Copy public assets (favicon, images, etc.)
COPY --from=builder /app/public ./public

# Copy the standalone server (includes only production node_modules)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Copy static assets generated by Next.js build
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Copy Prisma schema + generated client (needed at runtime for DB queries)
COPY --from=builder /app/prisma/schema.prisma ./prisma/schema.prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma

# Switch to non-root user
USER nextjs

# Render requires port 3000; Next.js standalone binds to this by default
EXPOSE 3000

# Set hostname to bind to all interfaces (required in containers)
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

# Healthcheck — Render also polls this independently, but this is useful
# for local Docker Desktop testing and docker-compose orchestration.
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1

# Start the standalone Next.js server
CMD ["node", "server.js"]
