-- CreateEnum (only if it doesn't exist)
DO $$ BEGIN
    CREATE TYPE "TourBlockReason" AS ENUM ('MISINFORMATION', 'INAPPROPRIATE_CONTENT', 'POLICY_VIOLATION', 'MISSING_INFO', 'SPAM', 'FALSE_CLAIMS', 'COPYRIGHT_VIOLATION', 'UNAUTHORIZED_CONTACT', 'LEGAL_VIOLATION', 'UNETHICAL_BEHAVIOR', 'SAFETY_CONCERN', 'OTHER');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- AlterTable
ALTER TABLE "tours" ADD COLUMN IF NOT EXISTS "isBlocked" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "tours" ADD COLUMN IF NOT EXISTS "blockedBy" TEXT;
ALTER TABLE "tours" ADD COLUMN IF NOT EXISTS "blockedAt" TIMESTAMP(3);
ALTER TABLE "tours" ADD COLUMN IF NOT EXISTS "blockReason" "TourBlockReason";
ALTER TABLE "tours" ADD COLUMN IF NOT EXISTS "blockNotes" TEXT;
ALTER TABLE "tours" ADD COLUMN IF NOT EXISTS "unblockedBy" TEXT;
ALTER TABLE "tours" ADD COLUMN IF NOT EXISTS "unblockedAt" TIMESTAMP(3);

