-- CreateEnum (only if not exists)
DO $$ BEGIN
 CREATE TYPE "UserBlockReason" AS ENUM ('FRAUD', 'POLICY_VIOLATION', 'INAPPROPRIATE_BEHAVIOR', 'SPAM', 'FALSE_INFORMATION', 'UNAUTHORIZED_ACTIVITY', 'LEGAL_VIOLATION', 'UNETHICAL_BEHAVIOR', 'SAFETY_CONCERN', 'OTHER');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

-- AlterTable (only if columns don't exist)
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "isBlocked" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "blockedBy" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "blockedAt" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "blockReason" "UserBlockReason";
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "blockNotes" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "unblockedBy" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "unblockedAt" TIMESTAMP(3);

